/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.grupo9.vista.prestamo;

import javax.swing.BorderFactory;
import javax.swing.border.Border;

/**
 *
 * @author MICHELLE
 */
public class JfrmPrestamoLibros extends javax.swing.JFrame {

    /**
     * Creates new form JfrmPrestamoLibros
     */
    public JfrmPrestamoLibros() {
        initComponents();
        
        Border roundedBorder = new RoundedBorder(15); // Radio de 15
        txtBuscar.setBorder(roundedBorder);
        txtIdCliente.setBorder(roundedBorder);
        txtIdLibro.setBorder(roundedBorder);
        txtIdPrestamo.setBorder(roundedBorder);
        txtFechaLimite.setBorder(roundedBorder);
        txtFechaPestamo.setBorder(roundedBorder);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtIdLibro = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtIdCliente = new javax.swing.JTextField();
        txtBuscar = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txtIdPrestamo = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        txtFechaPestamo = new javax.swing.JFormattedTextField();
        txtFechaLimite = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(229, 229, 229));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(215, 216, 117));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(35, 26, 6));
        jLabel1.setText("PRÉSTAMOS DE LIBROS");

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/3839448_bank_build_business_loan_management_icon.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap(339, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel1))
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 80));

        jLabel2.setBackground(new java.awt.Color(35, 26, 6));
        jLabel2.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(35, 26, 6));
        jLabel2.setText("Fecha Préstamo: ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, -1, -1));

        txtIdLibro.setBackground(new java.awt.Color(215, 216, 117));
        txtIdLibro.setBorder(null);
        jPanel1.add(txtIdLibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 90, 20));

        jLabel3.setBackground(new java.awt.Color(124, 120, 116));
        jLabel3.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(124, 120, 116));
        jLabel3.setText("Registro del préstamo - formulario");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, -1, -1));

        jLabel4.setBackground(new java.awt.Color(35, 26, 6));
        jLabel4.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(35, 26, 6));
        jLabel4.setText("Fecha límite de devolución:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 200, -1, -1));

        jLabel5.setBackground(new java.awt.Color(35, 26, 6));
        jLabel5.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(35, 26, 6));
        jLabel5.setText("ID Libro:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, -1, -1));

        jLabel6.setBackground(new java.awt.Color(35, 26, 6));
        jLabel6.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(35, 26, 6));
        jLabel6.setText("ID Cliente:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, -1, -1));

        jLabel7.setBackground(new java.awt.Color(35, 26, 6));
        jLabel7.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(35, 26, 6));
        jLabel7.setText("Estado del préstamo:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, -1, -1));

        jLabel8.setBackground(new java.awt.Color(35, 26, 6));
        jLabel8.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(35, 26, 6));
        jLabel8.setText("Multas:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 230, -1, -1));

        jLabel9.setBackground(new java.awt.Color(35, 26, 6));
        jLabel9.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(35, 26, 6));
        jLabel9.setText("ID Préstamo:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, -1, -1));

        txtIdCliente.setBackground(new java.awt.Color(215, 216, 117));
        txtIdCliente.setBorder(null);
        jPanel1.add(txtIdCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 90, 20));

        txtBuscar.setBackground(new java.awt.Color(215, 216, 117));
        txtBuscar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtBuscar.setForeground(new java.awt.Color(102, 102, 102));
        txtBuscar.setText("Buscar...");
        txtBuscar.setBorder(null);
        jPanel1.add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 350, 310, 40));

        jButton1.setBackground(new java.awt.Color(215, 216, 117));
        jButton1.setFont(new java.awt.Font("Stencil", 0, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(35, 26, 6));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/510861_find_magnifying glass_search_zoom_icon.png"))); // NOI18N
        jButton1.setText("Consultar");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 350, 130, 40));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NO PENDIENTES", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 230, 140, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ACTIVO", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 230, 80, -1));

        jButton2.setBackground(new java.awt.Color(215, 216, 117));
        jButton2.setFont(new java.awt.Font("Stencil", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(35, 26, 6));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/103409_text_add_book_icon.png"))); // NOI18N
        jButton2.setText("Registrar");
        jButton2.setBorder(null);
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 130, 40));

        jButton3.setBackground(new java.awt.Color(215, 216, 117));
        jButton3.setFont(new java.awt.Font("Stencil", 0, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(35, 26, 6));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/8666681_edit_icon (1).png"))); // NOI18N
        jButton3.setText("Actualizar");
        jButton3.setBorder(null);
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, 130, 40));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Prestamo", "ID Libro", "ID Cliente", "Fecha prestamo", "Fecha limite", "Estado", "Multas"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 730, 150));

        txtIdPrestamo.setBackground(new java.awt.Color(215, 216, 117));
        txtIdPrestamo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.add(txtIdPrestamo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 90, 20));

        jButton4.setBackground(new java.awt.Color(215, 216, 117));
        jButton4.setFont(new java.awt.Font("Stencil", 0, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(35, 26, 6));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/8664938_trash_can_delete_remove_icon.png"))); // NOI18N
        jButton4.setText("Eliminar");
        jButton4.setBorder(null);
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 280, 120, 40));

        txtFechaPestamo.setBackground(new java.awt.Color(215, 216, 117));
        jPanel1.add(txtFechaPestamo, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 202, 100, 20));

        txtFechaLimite.setBackground(new java.awt.Color(215, 216, 117));
        jPanel1.add(txtFechaLimite, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 200, 110, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 810, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 609, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JFormattedTextField txtFechaLimite;
    private javax.swing.JFormattedTextField txtFechaPestamo;
    private javax.swing.JTextField txtIdCliente;
    private javax.swing.JTextField txtIdLibro;
    private javax.swing.JTextField txtIdPrestamo;
    // End of variables declaration//GEN-END:variables
}
